name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH Agent
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

      - name: Deploy app
        run: |
          DEPLOY_DIR="/var/www/sukaair/"

          # Clone your GitHub repository into the directory
          git clone https://github.com/GadoGadoEnjoyer/vote.git "$DEPLOY_DIR"

          # Additional deployment steps, if needed
          # For example, you might need to install dependencies, build your project, etc.

          # Optionally, restart your web server to apply changes
          # Replace 'your-web-server-command' with the appropriate command for your server
          # sudo your-web-server-command
          
          echo "Deployment successful to $DEPLOY_DIR"
