name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            # Create a directory for your project in /var/www/
            mkdir -p /var/www/sukaair/

            # Clone your GitHub repository into the /var/www/sukaair/ directory
            cd /var/www/sukaair/
            git clone git@github.com:GadoGadoEnjoyer/vote.git

            # Additional deployment steps, if needed
            # For example, you might need to install dependencies, build your project, etc.
            
            # Optionally, restart your web server to apply changes
            # Replace 'your-web-server-command' with the appropriate command for your server
            # sudo your-web-server-command

            echo 'Deployment successful to /var/www/sukaair/'
