name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH Agent
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

      - name: Deploy app
        run: |
          cd /var/www
          ls -la
          sudo git clone https://github.com/GadoGadoEnjoyer/vote.git 
          
          echo "Deployment successful"
